# Travis Continuous Integration Configuration File, based on ..
#   Generic MoveIt Travis Continuous Integration Configuration File
#   Works with all MoveIt! repositories/branches
#   Author: Dave Coleman, Jonathan Bohren
language:
  - cpp
  - python
python:
  - "2.7"
compiler:
  - gcc
env:
  - ROS_DISTRO=groovy ROSWS=rosws  BUILDER=rosbuild
  - ROS_DISTRO=groovy ROSWS=wstool BUILDER=catkin
  - ROS_DISTRO=hydro  ROSWS=wstool BUILDER=catkin
notifications:
  email:
    recipients:
      - k-okada@jsk.t.u-tokyo.ac.jp
      - iisaito@opensource-robotics.tokyo.jp
    on_success: always #[always|never|change] # default: change
    on_failure: always #[always|never|change] # default: always
before_install: # Use this to prepare the system to install prerequisites or dependencies
  # Define some config vars
  - export CI_SOURCE_PATH=$(pwd)
  - export REPOSITORY_NAME=${PWD##*/}
  - echo "Testing branch $TRAVIS_BRANCH of $REPOSITORY_NAME"
  - sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu precise main" > /etc/apt/sources.list.d/ros-latest.list'
  - wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y python-catkin-pkg python-rosdep python-wstool ros-$ROS_DISTRO-catkin ros-$ROS_DISTRO-ros
  - if [ $ROSWS == rosws ]; then sudo apt-get install -qq -y python-rosinstall; fi
  # Setup rosdep
  - sudo rosdep init
  - rosdep update
install: # Use this to install any prerequisites or dependencies necessary to run your build
  # Create workspace
  - mkdir -p ~/ros/ws_$REPOSITORY_NAME/src
  - cd ~/ros/ws_$REPOSITORY_NAME/src
  - $ROSWS init .
  - $ROSWS merge http://raw.github.com/$TRAVIS_REPO_SLUG/$TRAVIS_BRANCH/.rosinstall
  - if [ $ROSWS == rosws ]; then $ROSWS merge /opt/ros/$ROS_DISTRO/.rosinstall; fi
  - sed -i "s@^\(.*github.com/$TRAVIS_REPO_SLUG.*\)@#\1@" .rosinstall # comment out current repo
  - $ROSWS update
  - $ROSWS set $REPOSITORY_NAME http://github.com/$TRAVIS_REPO_SLUG --git -y
  - ln -s $CI_SOURCE_PATH . # Link the repo we are testing to the new workspace
  - cd ../
  # Install dependencies for source repos
  - rosdep install -r -n --from-paths src --ignore-src --rosdistro $ROS_DISTRO -y
before_script: # Use this to prepare your build for testing e.g. copy database configurations, environment variables, etc.
  - source /opt/ros/$ROS_DISTRO/setup.bash
  - if [ $ROSWS == rosws ]; then source src/setup.bash; fi
script: # All commands must exit with code 0 on success. Anything else is considered failure.
  - find . \! -path "*/.*" -type f | xargs egrep -i "(hoge|fuga)" ; if [ $? == 0 ]; then exit 1; fi
  - rospack profile
  - if [ $BUILDER == catkin ]; then catkin_make;      else rosmake -a --profile;      fi
  - if [ $BUILDER == catkin ]; then catkin_make test; else rosmake -a --test-only;    fi
  - if [ $BUILDER == catkin ]; then catkin_make install;      fi
  - if [ $BUILDER == catkin ]; then rm -fr devel src build;   fi
  - if [ $BUILDER == catkin ]; then source install/setup.bash;fi
  - if [ $BUILDER == catkin ]; then find install -iname "*.test" -print0 | xargs -0 -n1 rostest;      fi
after_failure:
  - if [ -e ./build/Testing/Temporary/LastTest.log ]; then cat ./build/Testing/Temporary/LastTest.log; fi
  - find ${HOME}/.ros/test_results -type f -exec echo "== {} ==" \; -exec cat {} \;
  - for file in ${HOME}/.ros/log/rostest-*; do echo "=== $file ==="; cat $file; done

